-   id: fmt
    name: fmt
    description: Format files with go fmt.
    entry: go fmt
    language: system
    files: \.go$
-   id: vet
    name: vet
    description: Check files with go vet.
    entry: go vet
    language: system
    files: \.go$
