-   id: fmt
    name: fmt
    description: Format files with go fmt.
    entry: fmt.sh
    language: script
    files: \.go$
-   id: vet
    name: vet
    description: Check files with go vet.
    entry: vet.sh
    language: script
    files: \.go$
