-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pre-commit
    sha: 6e5ac079273c1499add3a85d9b5394d0f1ef1520
    hooks:
    -   id: validate_config
    -   id: validate_manifest
